import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Corner from "@/components/ui/corner";
import Button from "@/components/ui/button";
import Member from "@/components/ui/member";
import Episode from "@/components/ui/episode";

const karmatic = localFont({
  src: "../fonts/ka1.ttf",
  display: "swap",
  variable: "--karmatic",
});
const eightBit = localFont({
  src: "../fonts/8bitArcadeIn.ttf",
  display: "swap",
  variable: "--eightBit",
});
export const metadata: Metadata = {
  title: "Odyssey",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${eightBit.variable} ${karmatic.variable} relative py-8 min-h-screen mx-auto bg-secondary`}
      >
        {children}
        <div className="w-full h-[24.5vw] bg-dark relative">
          <Corner
            backgroundColor={"bg-dark"}
            secondaryColor={"bg-primary"}
            direction={"topRight"}
          />
          <Corner
            backgroundColor={"bg-dark"}
            secondaryColor={"bg-primary"}
            direction={"bottomRight"}
          />
          <Corner
            backgroundColor={"bg-dark"}
            secondaryColor={"bg-primary"}
            direction={"topLeft"}
          />
          <Corner
            backgroundColor={"bg-dark"}
            secondaryColor={"bg-primary"}
            direction={"bottomLeft"}
          />
        </div>
        hello
        <div className="w-full h-24 flex justify-center items-center">
          <Button children="Listen Now" />
        </div>
        <Member image={"image"} name={"Ira Glass"} post={"Sound Manager"} />
        <div className="flex justify-around items-end mx-10 h-96 ">
          <Episode />
          <Episode />
          <Episode />
        </div>
      </body>
    </html>
  );
}
